# Generated by Django 5.2.8 on 2025-11-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=255, unique=True)),
                ('PasswordHash', models.CharField(max_length=255)),
                ('Is2FAEnabled', models.BooleanField(default=False)),
                ('Secret2FA', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
